services:

  mflix-app:
    build: 
      context: ./mflix/app
      dockerfile: Dockerfile
    container_name: mflix-app
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGODB_HOST=mflix-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=mflix
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    networks:
      - ntwrk
    depends_on:
      - mflix-db

  mflix-db:
    image: mongo:5.0
    container_name: mflix-db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mflix
    volumes:
      - td_mongodb_data:/data/db
    networks:
      - ntwrk

  mflix-mongo-express:
    image: mongo-express:latest
    container_name: mflix-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mflix-db:27017/mflix?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    networks:
      - ntwrk
    depends_on:
      - mflix-db

networks:
  ntwrk:
    driver: bridge

volumes:
  td_mongodb_data:
  
